### PR TITLE
Add docker setup with localtunnel to facilitate https on mobile AR devices

### PR DESCRIPTION
**Pull request by LeszekBlazewski**
hey @damiankoper!

Check this out.

We have to optimize the file sizes a little and we are good to go!
The startup is slow but then it rocks 🚀  and hot reload works gr8 m8

Cheers!

Please kindly accept me!

Here is a meme for all my fellow programmers!

meme

(Sorry for the new team member lblazewski 😅 ). No worries Luke is a great guy and will try his best!

### CODE REVIEW

**Comment by damiankoper** [comment]
Convince me how is it more convenient than standard port forwarding with local remote debugging?

**Comment by LeszekBlazewski** [comment]
W8, how do you want to access AR/VR webXR api on plain local http?

Those are in same category as service workers, to have a valid session they require encrypted connection with SSL/TLS (https).

How do you achieve such requirement locally? (self signed cert does not work AFAiK)

**Comment by damiankoper** [comment]
`localhost` is treated as a safe context. Just use port forwarding in `chrome://inspect`. It can also be configured over WiFi (default USB) but with some `adb` tricks. I will describe it tomorrow during our meeting.

**Comment by LeszekBlazewski** [comment]
Ohhhh, I tried going the default route for accessing http://$PC_IP:8080 but this is not safe of course. Didn't know about the safe localhost stuff. Anyway, then this won't be needed but it's a cool feature cuz we can share the environment with anyone just by providing them the link 😄

**Pull request closed without merging**
